server:
  port: @server.port@
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    max-active: 10
    min-idle: 0
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
    timeout: @spring.redis.timeout@
#    password: @spring.redis.password@
    lettuce:
      pool:
        max-active: @spring.redis.pool.max-active@
        max-idle: @spring.redis.pool.max-idle@
        max-wait: @spring.redis.pool.max-wait@
        min-idle: @spring.redis.pool.min-idle@
mybatis:
  mapper-locations: classpath:mapper/*.xml
data:
  address: @data.address@
  port: @data.port@
osprey:
  bourses:
    okcoin:
      name: @osprey.bourses.okcoin.name@
      url: @osprey.bourses.okcoin.url@
    huobi:
      name: @osprey.bourses.huobi.name@
      url: @osprey.bourses.huobi.url@