server:
  port: @server.port@
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:  @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    max-active: 10
    min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
data:
  address: @data.address@
  port: @data.port@
osprey:
  bourses:
    okcoin:
      name: @osprey.bourses.okcoin.name@
      url: @osprey.bourses.okcoin.url@
    huobi:
      name: @osprey.bourses.huobi.name@
      url: @osprey.bourses.huobi.url@